### ISSUE TITLE
zadanie mobile

### ISSUE THREAD

**Issue by K4PEK** [Solvro/rekrutacja.zima.2023#1]
Czy w poleceniu odnośnie wyświetlania, dodawania itd zadań chodzi o to aby, stworzyć jeden projekt i te zadanie to jego taski [ /project/{projectId}/task ] , czy kazde zadanie ma byc osobnym projektem [ /project/ ]

**Comment by jakubandrzejewski0402** [comment]
Dokładnie tak jak napisałeś, chodzi o to aby stworzyć projekt i dodawać do niego taski.
